name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: mostafag95
  DOCKER_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t "$DOCKER_USERNAME/django:$GITHUB_SHA" .
        docker images

    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin -H
      
    - name: Push Docker Image
      run: |
        docker push "$DOCKER_USERNAME/django:$GITHUB_SHA"
