name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: mostafag95
  DOCKER_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: "${{ env.DOCKER_USERNAME }}/django:${{ env.GITHUB_SHA }}"

    - name: Push Docker Image
      uses: docker/push-action@v2
      with:
        tags: "${{ env.DOCKER_USERNAME }}/django:${{ env.GITHUB_SHA }}"
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.PASSWORD }}
